### PR TITLE
Implement multi-threading support

### PR DESCRIPTION
**Pull request by F-JJTH**
This patch implement multi-threading for QTiles.
Here on my Intel i7 with 8 cores it definitely speed up the rendering.

It is also possible to implement a GUI option like "Number of threads allowed to use: x" then the user can select the number of thread instead of using all threads available. I leave you implement it if you feel it mandatory.

I took the liberty to create the "options" dictionnary for TilingThread constructor only for readability (very long line are not easy to read)

Hoping this patch is welcome
Regards,
Clément

### CODE REVIEW

**Comment by F-JJTH** [comment]
hmmm I just realize that my patch only works for x/y/z export.
imEven it break MBTiles, ZIP, ... export. I guess multi threading must be limited to x/y/z export

**Comment by simgislab** [comment]
Thanks. We probably won't merge, but you inspired our own implementation of multi-threading today) Check it out here: https://github.com/nextgis/QTiles/tree/multithreading

**Comment by F-JJTH** [comment]
Nice ! I will follow this branch with lot of interest.

**Comment by robinpaulson** [comment]
Hi, it'd be great to get this merged into master, it worked very well when I tried it. Are there any particular problems with it?

Cheers

**Pull request closed without merging**
