### PR TITLE
tweaks to map viewer

### PR DESCRIPTION
**Pull request by robinpaulson**
Make the map fit the screen, with a 10 pixel gap around the edge

### CODE REVIEW

**Comment by robinpaulson** [comment]
Adds part of https://github.com/nextgis/QTiles/issues/66

**Comment by kannes** [comment]
Why a gap at all? I would suggest proper full window fill.

**Comment by robinpaulson** [comment]
@kannes sure, sounds good. There is little change or progress on this repo though, bugs are not fixed, etc.

**Comment by simgislab** [comment]
>It is almost abandonware.
This is not true.

**Comment by robinpaulson** [comment]
>> It is almost abandonware.

> This is not true.

One commit in the last year (to update the Readme!).
Many bugs gone unfixed.
3 pull requests which haven't been denied or accepted.
Little meaningful engagement on open issues.

**Comment by simgislab** [comment]
The approach you've chosen is not constructive

1. It doesn't matter how many commits is there for the software if it simply **works**. We don't have intention to regularly commit to all 30+ of our QGIS plugins.

2. The major PR was not merged because it required serious commitment on our side. Two smaller ones could be merged. I won't comment on the last one as it just appeared. So it leaves us only with one - yours. A reminder without aggressive labeling would suffice.

3. Number of bugs is very minimal, bugs are well discussed, none of them we see as critical. If you care to provide PR with fixes - please do. If you particularly care about certain bugs, please follow up in the threads.

**Comment by robinpaulson** [comment]
> bugs are well discussed

you've never said a word on this, it's a blocker for me, to the point i dropped your plugin and went elsewhere.

https://github.com/nextgis/QTiles/issues/70

there are others, the same situation.

**Pull request merged**
